@startuml wf-08-account
!include _chrome.iuml
title Wireframe - Account - showaccount.xhtml / updateaccount.xhtml (UC09 View / Update Account)
salt
{+
$navbar("Welcome Anakin | Log out")
==
<b>Account
{
  <b>Personal information | . | <b>Address | .
  Login | "anakin    " | Street 1 | "3 Wars Street"
  First name | "Anakin    " | Street 2 | "          "
  Last name | "Skywalker " | City | "Black Star"
  E-mail | "anakin@... " | State | "          "
  Telephone | "+1 123 ..." | Zip code | "9999      "
  Date of birth | "01/07/1935" | Country | "Venezuela "
  Age | "91        " | . | .
}
[Edit]
$footer()
}
@enduml
