#!/usr/bin/env python3
"""
Generate one Markdown page per PlantUML diagram so that every page carries
BOTH the rendered image and the exact PlantUML source it was rendered from.

  docs/uml/src/<category>/<name>.puml   (source of truth, edited by humans)
      -> docs/uml/rendered/<category>/<name>.png|svg   (render.sh)
      -> docs/uml/markdown/<category>/<name>.md        (this script)
      -> docs/uml/markdown/README.md                   (index)

Metadata is read from two header comments in each .puml file:
  ' @kind: <UML 2.5.1 diagram kind>
  ' @summary: <one-sentence description>

It also verifies traceability: every `ref` InteractionUse and every "ref/see sd|stm|act <Name>"
note must resolve to a diagram whose Annex A frame heading is "<kind> <Name>", every diagram file
named in a legend must exist, and every source must have a rendered PNG and SVG.

Run:  python3 docs/uml/gen_markdown.py          (write pages; exit 1 on trace errors)
      python3 docs/uml/gen_markdown.py --check  (exit 1 if pages are stale or trace errors; for CI)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT / "markdown"
CATEGORIES = [
    ("structure", "Structure diagrams"),
    ("behaviour", "Behaviour diagrams"),
    ("patterns", "Design pattern diagrams"),
]
HEADING_RE = re.compile(r"^mainframe\s+\*\*(\w[\w ]*)\*\*\s*(.*)$", re.M)
TITLE_RE = re.compile(r"^title\s+(.*)$", re.M)
META_RE = re.compile(r"^'\s*@(kind|summary):\s*(.*)$", re.M)
# InteractionUse in an interaction overview:  :**ref**\n<Name>;
REF_BLOCK_RE = re.compile(r"\*\*ref\*\*\s*\n\s*([A-Za-z]\w*)")
# Textual cross-references in notes:  "ref sd Name", "see sd Name", "see stm Name"
REF_TEXT_RE = re.compile(r"\b(?:ref|see)\s+(sd|stm|act)\s+([A-Z]\w*)")
# Diagram file names quoted in legends/tables:  | 13e-sequence-browse-catalogue |
FILE_RE = re.compile(r"\|\s*(\d\d[a-z]?-[a-z0-9-]+)\s*\|")
BANNER = "<!-- GENERATED by docs/uml/gen_markdown.py from the .puml source. Do not edit by hand. -->"


def meta_of(text: str) -> dict[str, str]:
    m = dict(META_RE.findall(text))
    heading = HEADING_RE.search(text)
    title = TITLE_RE.search(text)
    m["frame"] = f"{heading.group(1)} {heading.group(2)}".strip() if heading else ""
    m["title"] = title.group(1).strip() if title else ""
    return m


def frame_name(m: dict[str, str]) -> tuple[str, str]:
    kind, _, rest = m["frame"].partition(" ")
    return kind, (rest.split()[0] if rest.split() else "")


# UML 2.5.1 Annex A: permitted frame kinds (long form and abbreviation).
ANNEX_A_KINDS = {"activity": "act", "class": "class", "component": "cmp", "deployment": "dep",
                 "interaction": "sd", "package": "pkg", "state machine": "stm", "use case": "uc"}
# Expected frame kind per diagram type. The heading names the kind of the enclosing namespace
# or owning element (Annex A): Interactions -> sd (clause 17.2.4.1, for sequence, communication,
# interaction overview and timing diagrams); class/object/package/profile diagrams of a package -> pkg;
# composite structure of a class -> class.
EXPECTED_KIND = {"Sequence": "sd", "Communication": "sd", "Interaction Overview": "sd", "Timing": "sd",
                 "Activity": "act", "State Machine": "stm", "Use Case": "uc", "Component": "cmp",
                 "Deployment": "dep", "Composite Structure": "class", "Class": "pkg", "Object": "pkg",
                 "Package": "pkg", "Profile": "pkg"}


def heading_errors(name: str, m: dict[str, str]) -> list[str]:
    kind, fname = frame_name(m)
    errs = []
    if kind not in set(ANNEX_A_KINDS.values()):
        errs.append(f"{name}: frame kind '{kind}' is not an Annex A frame kind")
    base = m.get("kind", "").split(" (")[0]
    if base in EXPECTED_KIND and kind != EXPECTED_KIND[base]:
        errs.append(f"{name}: {base} diagram must use frame kind '{EXPECTED_KIND[base]}', found '{kind}'")
    if not re.fullmatch(r"[A-Za-z_][\w:.]*", fname or ""):
        errs.append(f"{name}: frame name '{fname}' must be a (qualified) element name")
    return errs


# UML 2.5.1 Annex C keywords and Clause 22 Standard Profile stereotypes (case-insensitive match).
UML_KEYWORDS = {
    "abstraction", "access", "activity", "actor", "apply", "artifact", "bind", "centralbuffer", "collaboration",
    "component", "datatype", "datastore", "decisioninput", "decisioninputflow", "deploy", "deployment spec",
    "device", "enumeration", "executionenvironment", "extend", "external", "flow", "import", "include",
    "information", "interface", "iterative", "localpostcondition", "localprecondition", "manifest", "merge",
    "model", "multicast", "multireceive", "occurrence", "parallel", "postcondition", "precondition", "primitive",
    "profile", "protocol", "representation", "selection", "signal", "singleexecution", "statemachine", "stream",
    "use", "stereotype", "metaclass",
    # Standard Profile (Table 22.1)
    "auxiliary", "buildcomponent", "call", "create", "derive", "destroy", "document", "entity", "executable",
    "file", "focus", "framework", "implement", "implementationclass", "instantiate", "library", "metamodel",
    "modellibrary", "process", "realization", "refine", "responsibility", "script", "send", "service", "source",
    "specification", "subsystem", "systemmodel", "trace", "type", "utility",
}
# PlantUML directives written in guillemets that are not UML labels
PLANTUML_DIRECTIVES = {"choice", "fork", "join", "end", "entrypoint", "exitpoint", "history", "history*"}
STEREO_RE = re.compile(r"<<([^<>]+)>>")


def profile_stereotypes(sources: dict[str, tuple[str, str]]) -> set[str]:
    names = set()
    for cat, text in sources.values():
        names |= {m.lower() for m in re.findall(r"class (\w+) <<stereotype>>", text)}
    return names


def stereotype_errors(sources: dict[str, tuple[str, str]]) -> list[str]:
    allowed = UML_KEYWORDS | PLANTUML_DIRECTIVES | profile_stereotypes(sources)
    errs = []
    for name, (cat, text) in sorted(sources.items()):
        body = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("'"))
        for grp in STEREO_RE.findall(body):
            for st in (x.strip() for x in grp.split(",")):
                if st.lower() not in allowed:
                    errs.append(f"{name}: <<{st}>> is neither a UML 2.5.1 keyword / standard stereotype nor defined in a profile (09)")
    return errs


def trace(sources: dict[str, tuple[str, str]]) -> tuple[list[tuple[str, str, str, str]], list[str]]:
    """Resolve every cross-diagram reference. Returns (rows, errors).
    rows = (source diagram, reference, target diagram or '', status)."""
    frames: dict[tuple[str, str], str] = {}
    for name, (cat, text) in sources.items():
        kind, fname = frame_name(meta_of(text))
        frames[(kind, fname)] = name
    rows, errors = [], []
    for name, (cat, text) in sorted(sources.items()):
        body = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("'"))
        refs = [("sd", r) for r in REF_BLOCK_RE.findall(body)] + REF_TEXT_RE.findall(body)
        for kind, target in dict.fromkeys(refs):
            hit = frames.get((kind, target))
            rows.append((name, f"{kind} {target}", hit or "", "resolved" if hit else "MISSING"))
            if not hit:
                errors.append(f"{name}: reference '{kind} {target}' has no diagram with frame '{kind} {target}'")
        for f in dict.fromkeys(FILE_RE.findall(body)):
            ok = f in sources
            rows.append((name, f"file {f}", f if ok else "", "resolved" if ok else "MISSING"))
            if not ok:
                errors.append(f"{name}: legend names file '{f}' which does not exist")
    return rows, errors


def page(cat: str, puml: Path, style: str, refs_out: list, refs_in: list) -> str:
    text = puml.read_text(encoding="utf-8").rstrip() + "\n"
    m = meta_of(text)
    name = puml.stem
    return f"""{BANNER}
# {m['title'] or name}

| Property | Value |
|---|---|
| UML 2.5.1 diagram kind | {m.get('kind', '')} |
| Frame heading (Annex A) | `{m['frame']}` |
| Summary | {m.get('summary', '')} |
| PlantUML source | [`src/{cat}/{name}.puml`](../../src/{cat}/{name}.puml) |
| Rendered | [PNG](../../rendered/{cat}/{name}.png) · [SVG](../../rendered/{cat}/{name}.svg) |
| References | {", ".join(f"[{r}](../{c}/{t}.md)" for r, c, t in refs_out) or "none"} |
| Referenced by | {", ".join(f"[{t}](../{c}/{t}.md)" for c, t in refs_in) or "none"} |

## Diagram

![{m['title'] or name}](../../rendered/{cat}/{name}.png)

## PlantUML source

The block below is the exact content of `src/{cat}/{name}.puml`. It includes the shared
style file `../_style.iuml` (reproduced underneath) so it renders identically in any
PlantUML tool when saved next to that file.

```plantuml
{text}```

<details>
<summary>Shared style: <code>src/_style.iuml</code></summary>

```plantuml
{style}```

</details>

[Back to index](../README.md)
"""


def index(entries: list[tuple[str, str, dict[str, str]]], rows, catof) -> str:
    out = [BANNER, "# PetStore EE7 UML 2.5.1 model - diagram pages", "",
           "Each page shows the rendered PNG and the PlantUML source it was rendered from.",
           "See the [model README](../README.md) for conformance notes and findings.", ""]
    for cat, label in CATEGORIES:
        out += [f"## {label}", "", "| # | Diagram | UML kind | Summary |", "|---|---|---|---|"]
        for c, name, m in entries:
            if c == cat:
                num = name.split("-", 1)[0]
                out.append(f"| {num} | [{m['title'] or name}]({cat}/{name}.md) | {m.get('kind', '')} | {m.get('summary', '')} |")
        out.append("")
    out += ["## Traceability matrix (cross-diagram references)", "",
            "Generated by resolving every `ref` InteractionUse, every `ref/see sd|stm|act <Name>` note and every",
            "diagram file named in a legend against the frame headings (Annex A) of the diagrams in this model.", "",
            "| Source diagram | Reference | Target diagram | Status |", "|---|---|---|---|"]
    for src_, ref, tgt, st in rows:
        tcell = f"[{tgt}]({catof[tgt]}/{tgt}.md)" if tgt else "-"
        out.append(f"| [{src_}]({catof[src_]}/{src_}.md) | `{ref}` | {tcell} | {st} |")
    out.append("")
    return "\n".join(out)


def build() -> tuple[dict[Path, str], list[str]]:
    style = (SRC / "_style.iuml").read_text(encoding="utf-8").rstrip() + "\n"
    sources: dict[str, tuple[str, str]] = {}
    for cat, _ in CATEGORIES:
        for puml in sorted((SRC / cat).glob("*.puml")):
            sources[puml.stem] = (cat, puml.read_text(encoding="utf-8"))
    catof = {n: c for n, (c, _) in sources.items()}
    rows, errors = trace(sources)
    errors.extend(stereotype_errors(sources))
    files: dict[Path, str] = {}
    entries = []
    for name, (cat, text) in sources.items():
        m = meta_of(text)
        if "kind" not in m or "summary" not in m:
            errors.append(f"{name}: missing ' @kind: or ' @summary: header")
        errors.extend(heading_errors(name, m))
        for ext in ("png", "svg"):
            if not (ROOT / "rendered" / cat / f"{name}.{ext}").exists():
                errors.append(f"{name}: rendered/{cat}/{name}.{ext} not generated")
        refs_out = [(r, catof[t], t) for s_, r, t, st in rows if s_ == name and t and t != name]
        refs_in = [(catof[s_], s_) for s_, r, t, st in rows if t == name and s_ != name]
        refs_in = list(dict.fromkeys(refs_in))
        files[OUT / cat / f"{name}.md"] = page(cat, SRC / cat / f"{name}.puml", style, refs_out, refs_in)
        entries.append((cat, name, m))
    files[OUT / "README.md"] = index(entries, rows, catof)
    return files, errors


def main() -> int:
    files, errors = build()
    for e in errors:
        print(f"TRACE ERROR: {e}", file=sys.stderr)
    if "--check" in sys.argv:
        stale = [p for p, c in files.items() if not p.exists() or p.read_text(encoding="utf-8") != c]
        orphans = [p for p in OUT.rglob("*.md") if p not in files]
        for p in stale + orphans:
            print(f"stale: {p.relative_to(ROOT)}")
        return 1 if stale or orphans or errors else 0
    for p, c in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(c, encoding="utf-8")
    for p in OUT.rglob("*.md"):
        if p not in files:
            print(f"orphan (source removed, delete it): {p.relative_to(ROOT)}")
    print(f"Wrote {len(files)} Markdown pages into {OUT.relative_to(ROOT)}/")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
